[build]
command = "npm run build"

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable, s-maxage=31536000"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=300, stale-while-revalidate=30"
